name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: |
           pwd
           nproc
           uname -a
           ./configure --disable-multilib --enable-languages=c,c++ --disable-multilib --host=x86_64-pc-linux-gnu --target=x86_64-pc-linux-gnu --enable-deterministic-archives --disable-bootstrap --enable-default-pie --enable-default-ssp --disable-libssp --enable-linker-build-id --disable-libstdcxx-filesystem-ts

    - name: Make
      run: make

    - name: Run check
      run: |
           pwd

    - name: Run distcheck
      run: make distcheck
