name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: entorno
      run: |
           sudo apt update
           sudo apt upgrade
           sudo apt -y install binutils m4 autoconf libtool automake nasm pkgconf
    - name: configure
      run: |
           ./configure --disable-multilib --enable-languages=c,c++ --enable-multiarch --host=x86_64-pc-linux-gnu --target=x86_64-pc-linux-gnu --enable-deterministic-archives --disable-bootstrap --enable-default-pie --enable-default-ssp --disable-libssp --enable-linker-build-id --disable-libstdcxx-filesystem-ts --enable-shared --prefix=/home/runner/work/gcc/gcc/builds

    - name: make
      run: make

    - name: install
      run: make install

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: builds
